"""create books, authors, publsihers table

Revision ID: 39bc677068d9
Revises:
Create Date: 2025-02-02 09:03:05.239120

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39bc677068d9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("images", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("author_id"),
    )
    op.create_table(
        "publishers",
        sa.Column("publisher_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("publisher_id"),
    )
    op.create_table(
        "books",
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("book_title", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("publisher_id", sa.String(), nullable=False),
        sa.Column(
            "books_meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "media_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("publication_year", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=100), nullable=False),
        sa.Column(
            "cover_type",
            sa.Enum("PAPERBACK", "HARDBACK", name="cover_types"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.author_id"],
        ),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["publishers.publisher_id"],
        ),
        sa.PrimaryKeyConstraint("book_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    op.drop_table("publishers")
    op.drop_table("authors")
    # ### end Alembic commands ###
