"""changing book_id to string and added book_meta_data to order_items

Revision ID: 378885c4b6dc
Revises: 944862477e4f
Create Date: 2025-06-14 08:29:35.293050

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "378885c4b6dc"
down_revision = "944862477e4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop FK constraints first if needed
    op.drop_constraint(
        "cart_items_book_id_fkey", "cart_items", type_="foreignkey"
    )

    op.alter_column(
        "books",
        "book_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "cart_items",
        "book_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.add_column(
        "order_items",
        sa.Column(
            "book_meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.alter_column(
        "order_items",
        "book_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )

    # Re-add constraints
    op.create_foreign_key(
        "cart_items_book_id_fkey",
        "cart_items",
        "books",
        ["book_id"],
        ["book_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new FK constraints
    op.drop_constraint(
        "cart_items_book_id_fkey", "cart_items", type_="foreignkey"
    )

    op.alter_column(
        "order_items",
        "book_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.drop_column("order_items", "book_meta_data")
    op.alter_column(
        "cart_items",
        "book_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "books",
        "book_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # Recreate original foreign keys
    op.create_foreign_key(
        "cart_items_book_id_fkey",
        "cart_items",
        "books",
        ["book_id"],
        ["book_id"],
    )
    # ### end Alembic commands ###
