"""rename cart id & cart_item id column

Revision ID: e5a93f4de7d6
Revises: c325c39d6734
Create Date: 2025-06-05 10:49:27.410924

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e5a93f4de7d6"
down_revision = "c325c39d6734"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("carts", "id", new_column_name="cart_id")
    op.alter_column("cart_items", "id", new_column_name="cart_item_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cart_items", "cart_item_id", new_column_name="id")
    op.alter_column("carts", "cart_id", new_column_name="id")
    # ### end Alembic commands ###
