"""rename to total_amount and added user_meta_data to orders

Revision ID: 3aa40f69442e
Revises: 378885c4b6dc
Create Date: 2025-06-14 18:11:18.890212

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3aa40f69442e"
down_revision = "378885c4b6dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order_items", "price", new_column_name="total_amount")
    op.add_column(
        "orders",
        sa.Column(
            "user_meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "user_meta_data")
    op.alter_column("order_items", "total_amount", new_column_name="price")
    # ### end Alembic commands ###
